### ISSUE TITLE
Consider blinded color people

### ISSUE THREAD

**Issue by dpenas** [dpenas/roomsgame#4]
Right now the game is purely red, but later colors will be introduced. I have to consider the different color combinations in order to make it accesible to those who are color blinded. I've asked for feedback on Reddit about this: http://www.reddit.com/r/ColorBlind/comments/30pl76/questions_about_color_combination_for_open_source/

**Comment by davidtamayo177** [comment]
Hello! in order to cater to color blinded people as well, why not try to cater/focus on aspects of the game which do not rely on color that much?

Certain aspects could be size of a certain image or even the number of that certain image could relay important message to the players as well. So for example, determining a boss does not necessarily depend on color but size as well. 

You can also take a look into this link :)

http://jfly.iam.u-tokyo.ac.jp/color/

**Comment by davidtamayo177** [comment]
Also, in additon to my previous comment, if you want it to be accessible as possible to everyone, then try not to focus the goals of your game into something that comes necessary with colors. For example, in some games the only reason why you understand that a part of a boss' body is his weakness is because it is red, or its color emphasizes that certain part to be a weakness. Instead of doing that, why not indicate a boss' weakness by shapes, or any other factor that does not come necessary with color.

Hope this helped! Good luck on your game! :)

**Comment by dpenas** [comment]
Thank you so much for your advise! It has given me a great insight and it will totally help me :)

Thanks again!
